name: 'Run Tests'
description: 'Run unit tests and E2E tests'

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm install
      shell: bash

    - name: Run unit tests
      run: npm run test:run
      shell: bash

    - name: Install Playwright browsers
      run: npx playwright install --with-deps chromium
      shell: bash

    - name: Run E2E tests
      run: npm run test:e2e
      shell: bash

    - name: Generate test summary
      if: always()
      shell: bash
      run: |
        echo "# Test Results Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        # Parse unit test results
        if [ -f "test-results-unit/unit-tests.json" ]; then
          echo "## Unit Tests" >> $GITHUB_STEP_SUMMARY
          
          UNIT_TOTAL=$(jq -r '.numTotalTests // 0' test-results-unit/unit-tests.json)
          UNIT_PASSED=$(jq -r '.numPassedTests // 0' test-results-unit/unit-tests.json)
          UNIT_FAILED=$(jq -r '.numFailedTests // 0' test-results-unit/unit-tests.json)
          UNIT_SKIPPED=$(jq -r '.numPendingTests // 0' test-results-unit/unit-tests.json)
          
          echo "- **Total:** $UNIT_TOTAL" >> $GITHUB_STEP_SUMMARY
          echo "- **Passed:** ✅ $UNIT_PASSED" >> $GITHUB_STEP_SUMMARY
          echo "- **Failed:** ❌ $UNIT_FAILED" >> $GITHUB_STEP_SUMMARY
          echo "- **Skipped:** ⏭️ $UNIT_SKIPPED" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
        fi
        
        # Parse E2E test results
        if [ -f "test-results/e2e-tests.json" ]; then
          echo "## E2E Tests" >> $GITHUB_STEP_SUMMARY
          
          E2E_PASSED=$(jq -r '[.suites[].suites[]?.specs[]? | select(.ok == true)] | length' test-results/e2e-tests.json)
          E2E_FAILED=$(jq -r '[.suites[].suites[]?.specs[]? | select(.ok == false)] | length' test-results/e2e-tests.json)
          E2E_TOTAL=$((E2E_PASSED + E2E_FAILED))
          
          echo "- **Total:** $E2E_TOTAL" >> $GITHUB_STEP_SUMMARY
          echo "- **Passed:** ✅ $E2E_PASSED" >> $GITHUB_STEP_SUMMARY
          echo "- **Failed:** ❌ $E2E_FAILED" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
        fi

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          test-results/
          test-results-unit/
          playwright-report/
        retention-days: 5
